# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: 2022 Amazon Alexa Language Assisted Product Search Challenge
short_description: A landing page for the challenge
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description:  
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2022-09-23 00:00:00
end_date: 2023-04-10 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["mAP", "P@1", "max_AP", "min_AP"],
        "default_order_by": "mAP",
        "metadata": {
          "mAP": {
            "sort_ascending": False,
            "description": "Mean average precision for the returned images.",
          }
        }
    }
  - id: 2
    schema:
      {
        "labels": ["mAP", "P@1", "max_AP", "min_AP"],
        "default_order_by": "mAP",
        "metadata": {
          "mAP": {
            "sort_ascending": False,
            "description": "Mean average precision for the returned images.",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-10-12 00:00:00
    end_date: 2023-03-31 23:59:59
    test_annotation_file: annotations/product_expansion_annotated.jsonl
    codename: dev
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".jsonl"
  - id: 2
    name: Evaluation Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2023-03-09 00:00:00
    end_date: 2023-03-31 23:59:59
    test_annotation_file: annotations/evaluation_gt_file.jsonl
    codename: eval
    max_submissions_per_day: 5
    max_submissions_per_month: 20
    max_submissions: 20
    submission_meta_attributes:
      - name: Email
        description: POC Email
        type: text
        required: True
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".pkl"

dataset_splits:
  - id: 1
    name: Dev Split
    codename: val_split
  - id: 2
    name: Evaluation Split
    codename: eval_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
